---
# Source: drunk-app/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: test-your-app-name
  labels:
    helm.sh/chart: drunk-app-0.1.0
    app.kubernetes.io/name: your-app-name
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: your-app-name
    app.kubernetes.io/instance: test
