apiVersion: v2
name: drunk-hoppscotch
icon: https://github.com/baoduy/Images/raw/a0b73e4fcb03128ac7ece2a71ee2b40a9c33104d/NugetLogo.PNG
description: The drunkcoding template to deploy hoppscotch to Kubernetes
# A chart can be either an 'application' or a 'library' chart.
type: application
version: 1.0.0
appVersion: 'latest'

dependencies:
  - name: ingress-nginx
    alias: nginx
    version: 4.x.x
    condition: nginx.enabled
    repository: "https://kubernetes.github.io/ingress-nginx"

  - name: postgresql
    version: 15.x.x
    condition: postgresql.enabled
    repository: "https://charts.bitnami.com/bitnami"

  - name: drunk-app
    alias: app
    version: 1.x.x
    condition: app.enabled
    repository: "https://baoduy.github.io/hbd.charts/drunk-app"
