nginx:
  enabled: true
  tcp:
    54322: "hoppscotch/hoppscotch-postgresql:5432"

postgresql:
  enabled: true
  global:
    storageClass: 'hostpath'
  auth:
    enablePostgresUser: true
    postgresPassword: "7Ym33GEEwy9PhfE"
    username: "postgres"
    password: "7Ym33GEEwy9PhfE"
    database: "hoppscotch-db"

app:
  enabled: true
  deployment:
    enabled: true
    ports:
      app: 3000
      admin: 3100
      backend: 3170
  service:
    create: true
    type: ClusterIP
  global:
    image: 'hoppscotch/hoppscotch'
    tag: 'latest'
    initContainer:
      image: 'hoppscotch/hoppscotch-backend:latest'
      command: ["sh", "-c", "pnpm exec prisma migrate deploy"]
  secrets:
    #-----------------------Backend Config------------------------------#
    DATABASE_URL: "postgresql://postgres:7Ym33GEEwy9PhfE@hoppscotch-postgresql:5432/hoppscotch-db"
    # Auth Tokens Config
    JWT_SECRET: "7Ym33GEEwy9PhfE@123"
    TOKEN_SALT_COMPLEXITY: "10"
    MAGIC_LINK_TOKEN_VALIDITY: "3"
    REFRESH_TOKEN_VALIDITY: "604800000"
    ACCESS_TOKEN_VALIDITY: "86400000"
    SESSION_SECRET: "7Ym33GEEwy9PhfE@234"

    # Hoppscotch App Domain Config
    REDIRECT_URL: https://app.dev.local
    WHITELISTED_ORIGINS: https://app.dev.local,https://api.dev.local,https://admin.dev.local
    VITE_ALLOWED_AUTH_PROVIDERS: "MICROSOFT" #GOOGLE,GITHUB,MICROSOFT,EMAIL

    # Google Auth Config
    #GOOGLE_CLIENT_ID: "123456"
    #GOOGLE_CLIENT_SECRET: "123456"
    #GOOGLE_CALLBACK_URL: https://api.dev.local/v1/auth/google/callback
    #GOOGLE_SCOPE: email,profile

    # Github Auth Config
    #GITHUB_CLIENT_ID: "123456"
    #GITHUB_CLIENT_SECRET: "123456"
    #GITHUB_CALLBACK_URL: https://api.dev.local/v1/auth/github/callback
    #GITHUB_SCOPE: user:email

    # Microsoft Auth Config
    MICROSOFT_CLIENT_ID: "309e7d73-850b-46d7-91b6-3f659ced7978"
    MICROSOFT_CLIENT_SECRET: ""
    MICROSOFT_CALLBACK_URL: "https://api.dev.local/v1/auth/microsoft/callback"
    MICROSOFT_SCOPE: "openid profile user.read"
    MICROSOFT_TENANT: "d430a78c-dd8c-4515-bb49-b35ba765359f"

    # Mailer config
    MAILER_SMTP_URL: smtps://user@domain.com:pass@smtp.domain.com
    MAILER_ADDRESS_FROM: from@example.com
    
    # Rate Limit Config
    RATE_LIMIT_TTL: "60"
    RATE_LIMIT_MAX: "100"
    
    #-----------------------Frontend Config------------------------------#
    # Base URLs
    VITE_BASE_URL: "https://app.dev.local"
    VITE_SHORTCODE_BASE_URL: "https://app.dev.local"
    VITE_ADMIN_URL: "https://admin.dev.local"
    
    # Backend URLs
    VITE_BACKEND_GQL_URL: "https://api.dev.local/graphql"
    VITE_BACKEND_WS_URL: "wss://api.dev.local/graphql"
    VITE_BACKEND_API_URL: "https://api.dev.local/v1"
    
    # Terms Of Service And Privacy Policy Links (Optional)
    VITE_APP_TOS_LINK: https://docs.hoppscotch.io/support/terms
    VITE_APP_PRIVACY_POLICY_LINK: https://docs.hoppscotch.io/support/privacy
    
    ENABLE_SUBPATH_BASED_ACCESS: "false"

  tlsSecrets:
    dev-local:
      crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQ4RENDQXRpZ0F3SUJBZ0lVSkZUaXl3bm51ZEJPODVSUkx0bGQvTU90SGpnd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2dZMHhDekFKQmdOVkJBWVRBbE5ITVJJd0VBWURWUVFJREFsVGFXNW5ZWEJ2Y21VeEVqQVFCZ05WQkFjTQpDVk5wYm1kaGNHOXlaVEVTTUJBR0ExVUVDZ3dKUkdWMklFeHZZMkZzTVF3d0NnWURWUVFMREFORVRGVXhIakFjCkJna3Foa2lHOXcwQkNRRVdEMlZ0WVdsc1FHUmxkaTVzYjJOaGJERVVNQklHQTFVRUF3d0xLaTVrWlhZdWJHOWoKWVd3d0lCY05NalF3TkRBeU1UTXdNakExV2hnUE1qRXlOREF6TURreE16QXlNRFZhTUlHTk1Rc3dDUVlEVlFRRwpFd0pUUnpFU01CQUdBMVVFQ0F3SlUybHVaMkZ3YjNKbE1SSXdFQVlEVlFRSERBbFRhVzVuWVhCdmNtVXhFakFRCkJnTlZCQW9NQ1VSbGRpQk1iMk5oYkRFTU1Bb0dBMVVFQ3d3RFJFeFZNUjR3SEFZSktvWklodmNOQVFrQkZnOWwKYldGcGJFQmtaWFl1Ykc5allXd3hGREFTQmdOVkJBTU1DeW91WkdWMkxteHZZMkZzTUlJQklqQU5CZ2txaGtpRwo5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBNVoxdWxVV2ZDcmQ3Rkwwb2lFWXZZUjk3dlhCazZHckdEb2xuCmNodHBOdkNoNG1SbUtuejRtM05tQ2pUNW03cGJxWGlJazh6cE05a250a2E4ejZBRmFDYWEvc296aWE2V0VSOWIKWHZlem5pY0JRc3lDZ3NPb3Y0RFNDMC82VEpaKzhmcXlBWTNQL212djRlYlVPRWhuNlVlQXAzbEQvZDQyUlpBYQoxQi9LR1RLN0x6OVlSZUFNMDNMZnBHQkUwaStrQ1RTVGw1d0JRazJteUJ3S3cxYzhzU2llNnhGa2dnZ1BzOU9wCjBUa2dTYi9neFkzSHdxS0czOGRqb0lhMjVsVzNyOUIxdUViWjZGLy91dHVCT3p1MERZZE1LQ0ZRVlBtUUlNa3YKUkc0ZllOSFBUb2IxQ0d1d1RLK2IxWHJZazBzSG9FUVlSWnc5cFhIMnpYQm5UUjlJbFFJREFRQUJvMFF3UWpBaApCZ05WSFJFRUdqQVlnZ3NxTG1SbGRpNXNiMk5oYklJSlpHVjJMbXh2WTJGc01CMEdBMVVkRGdRV0JCUm5odUJuCnptcFNMNXpkMnBWVkUzNFJUbjVLUXpBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQXFMWUpwOTJmbHZyOWZnKzEKZkNIcWdmQm1jWlNjVUlwUEJBOFp4RjZHQXgrUkp6T09vR3dsK2p2Qm9CRU1jNlJFOHBjTGl2YlRmV0VUa1kwOQp3QmhyQzBHaWduQVd2UVZFdERNNkpnaEw5cXZwbjI0cXJMQ0VzUVFkU3RCRmF6MkF4M2wxQjZvbmg1VTZybCtICkZISzNSakJEdjJHekwrbFFRR1NPQjZHdzJvNlhLbW9iejA3OVJ4UVYzTlF1L2YzWm9tcE1SeE9aejBIVzRFUWEKYUdrRjMybUZGczVoQVJQdG5PcGZVVjYrK245ejI1Z044UVg5RDNIUXRuaGk5LzJDVnR4OUNRUFFJS2RhN3pETQpoZFIyUkZ0N3RjNm9MemxjckY3TDVHR2RJMlVEQnIyejlLdHRhOVZIaFlrUmRxajV5TnkxUDNDU0I0ZWY1bVV1CmhVYXVRQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRRGxuVzZWUlo4S3Qzc1UKdlNpSVJpOWhIM3U5Y0dUb2FzWU9pV2R5RzJrMjhLSGlaR1lxZlBpYmMyWUtOUG1idWx1cGVJaVR6T2t6MlNlMgpScnpQb0FWb0pwcit5ak9KcnBZUkgxdGU5N09lSndGQ3pJS0N3NmkvZ05JTFQvcE1sbjd4K3JJQmpjLythKy9oCjV0UTRTR2ZwUjRDbmVVUDkzalpGa0JyVUg4b1pNcnN2UDFoRjRBelRjdCtrWUVUU0w2UUpOSk9YbkFGQ1RhYkkKSEFyRFZ6eXhLSjdyRVdTQ0NBK3owNm5ST1NCSnYrREZqY2ZDb29iZngyT2docmJtVmJldjBIVzRSdG5vWC8rNgoyNEU3TzdRTmgwd29JVkJVK1pBZ3lTOUViaDlnMGM5T2h2VUlhN0JNcjV2VmV0aVRTd2VnUkJoRm5EMmxjZmJOCmNHZE5IMGlWQWdNQkFBRUNnZ0VBQU14L2FmMklCQjJIVEJjc1lPejlsVFRxMVVuaXovd3ZIRFhXS2t0MkhqN1EKRVYyUURXM0ozNkNUSmszdzRGM1JtOUZUaUZBYUw1Zjl6MkNIbjZGSzQ0WGUzQ3dQNmRhMXB2R1krOGVZMUdBRwpYUmtoQ3h0ckp0OW4yNm8za0xTbFZHb3UzRnFGOHJpbGFQL0lsVG1MUXdDQXJoUjU3QlF0MUNnZ0w4UzhpMEhrClBOOHJKd08zcktGWGdYdFVWMWVFQ0YzNVpEbDRrdlhnVDBlVGFuR3dxblRIZENZYVhzT1lQd2FCSm5EMjlzUjIKYzlhUFVlR2hpWW44d0RKMFNhVThBUzRBQzVBK3lKaEVUUHFsWGkxV2RscjRxOGEzMnVCYks0T3VKRTlmM081MgpQd2dtTndUVUNCYldQb2ZpdCt4dkJJWFlQQ1paUUxsYzU5UHVCWitHQVFLQmdRRDNWYzR6aXZtaDVBMDdFSi9oCmhvS1V2allyVDhtbDV5SXRwNmtncGwvQ0R5bmYvamIzKzhUWXlyelVSbGt1K1dGT1BVZkYwc0RQdEVWdGEyYXMKY1NjeDVuL09HcWd5aXQ3QzFzUXl6aFQxQ1BOa0luTmNaMGRYeWpoZXRxbFR5ckIxNUVaVnRjWGN0Tng2QkdBWApzQU92cEZnUU55TXY0SmdMc213NzJzNlE0UUtCZ1FEdHFMUjhHbndaczk3QTJHMS92QjRLN3VwM3h0cHhVKzFxCld2YWYvRWxTRENtRGYxRGIxT1lDa0tyWStNZm9vZHIxQUdaa1A2ZjdlR1J4Z2w1ZnJkdlQ2djV2OXg1RG5YTEMKT3B0b2N4aU45WDZMSE5KTDluRUxrajRjNm1ITFBpKy9DVDg0OVdnRDkyazJ2TCtHdDFHRDBvaGZwRVlUVFNSdwpnV0JvbElLS05RS0JnQXpEZXM2aUgxdkJYd1ZyU0RUbE1odm03UGl6TjE2K1hMOHFaY252akFXQnJ0R0dWdVBaCk5FRlR4UWJYVW9iZ0M2dHo4aDQ5VUFIbjlhVTk0NkNHZmxWTzVjMkhCcU1GRTVYT2EzV0x1UDBrSnh0Rnc5cEMKNGlXZm8rVVBYQkdjNWhwUFcyblU1WThNTGt5RnFVZlBwNEVLNUJpQ0graTZtRjRTS1ErMXJPOUJBb0dCQU1MdQovTk5LZWY0dkRnZkp2YzduQXhGZXRFejRlMVkzUytaUHBEakhtM0JENzQwZlViaHVvUmI3aUZjZGdBTnROd1o4CmhIKzN3dFkrQXMwajdMcTRCVGFHYXBwMTdJbnpUQnpLSzR4NTAyc2xNTjEwRDM0bExzWVo5djZLdFJvYThOalcKQWRoN1dnemUwNXNGS0dlY1Y2MHpjNDVYVk84aCtFQ2JyZk01MVBUOUFvR0FkbE1Pdm1sOUJOWDg3ekVaYXpOMgo5YmFMdFp1MG9kS1YxNkNRMmIxY05IUVZ3MEJTTEQxUlZNZVM1REpsdmM0bEptR25DMnJLb3lESFdOQjg2cERFCk8vT0J2SG5CM0hvYVZwelRPR3pyS29QYW5OWDlRTGwrNXYwSkJIUXRmVDBrWTlGbWVuUi9ieXBYNWc0cCtDUzgKcklpcmJHNC9GM0FpSHoyZmEyTkNQM289Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: app.dev.local
        port: 3000
      - host: api.dev.local
        port: 3170
      - host: admin.dev.local
        port: 3100
    tls: tls-dev-local