nginx:
  enabled: true
  tcp:
    54322: "hoppscotch/hoppscotch-postgresql:5432"

postgresql:
  enabled: true
  global:
    storageClass: 'hostpath'
  auth:
    enablePostgresUser: true
    postgresPassword: "7Ym33GEEwy9PhfE"
    username: "postgres"
    password: "7Ym33GEEwy9PhfE"
    database: "hoppscotch-db"

app:
  enabled: true
  deployment:
    enabled: true
    ports:
      app: 3000
      admin: 3100
      backend: 3170
  service:
    create: true
    type: ClusterIP
  global:
    image: 'hoppscotch/hoppscotch'
    tag: 'latest'
    port: 3000
    initContainer:
      image: 'hoppscotch/hoppscotch-backend:latest'
      command: ["/bin/sh", '-c', 'cd /usr/src/app/packages/hoppscotch-backend && pnpx prisma migrate deploy' ]
  secrets:
    #-----------------------Backend Config------------------------------#
    DATABASE_URL: "postgresql://postgres:7Ym33GEEwy9PhfE@hoppscotch-postgresql:5432/hoppscotch-db"
    # Auth Tokens Config
    JWT_SECRET: secretcode123
    TOKEN_SALT_COMPLEXITY: "10"
    MAGIC_LINK_TOKEN_VALIDITY: "3"
    REFRESH_TOKEN_VALIDITY: "604800000"
    ACCESS_TOKEN_VALIDITY: "86400000"
    SESSION_SECRET: anothersecretcode123

    # Hoppscotch App Domain Config
    REDIRECT_URL: http://localhost:3000
    WHITELISTED_ORIGINS: http://localhost:3170,http://localhost:3000,http://localhost:3100
    VITE_ALLOWED_AUTH_PROVIDERS: "MICROSOFT" #GOOGLE,GITHUB,MICROSOFT,EMAIL

    # Google Auth Config
    #GOOGLE_CLIENT_ID: "123456"
    #GOOGLE_CLIENT_SECRET: "123456"
    #GOOGLE_CALLBACK_URL: http://localhost:3170/v1/auth/google/callback
    #GOOGLE_SCOPE: email,profile

    # Github Auth Config
    #GITHUB_CLIENT_ID: "123456"
    #GITHUB_CLIENT_SECRET: "123456"
    #GITHUB_CALLBACK_URL: http://localhost:3170/v1/auth/github/callback
    #GITHUB_SCOPE: user:email

    # Microsoft Auth Config
    MICROSOFT_CLIENT_ID: "123456"
    MICROSOFT_CLIENT_SECRET: "123456"
    MICROSOFT_CALLBACK_URL: http://localhost:3170/v1/auth/microsoft/callback
    MICROSOFT_SCOPE: user.read
    MICROSOFT_TENANT: common

    # Mailer config
    MAILER_SMTP_URL: smtps://user@domain.com:pass@smtp.domain.com
    MAILER_ADDRESS_FROM: from@example.com
    
    # Rate Limit Config
    RATE_LIMIT_TTL: "60"
    RATE_LIMIT_MAX: "100"
    
    #-----------------------Frontend Config------------------------------#
    # Base URLs
    VITE_BASE_URL: "http://localhost:3000"
    VITE_SHORTCODE_BASE_URL: http://localhost:3000
    VITE_ADMIN_URL: http://localhost:3100
    
    # Backend URLs
    VITE_BACKEND_GQL_URL: http://localhost:3170/graphql
    VITE_BACKEND_WS_URL: wss://localhost:3170/graphql
    VITE_BACKEND_API_URL: http://localhost:3170/v1
    
    # Terms Of Service And Privacy Policy Links (Optional)
    VITE_APP_TOS_LINK: https://docs.hoppscotch.io/support/terms
    VITE_APP_PRIVACY_POLICY_LINK: https://docs.hoppscotch.io/support/privacy
    
    ENABLE_SUBPATH_BASED_ACCESS: "false"