apiVersion: v2
name: drunk-k8s-gateway
icon: https://drunkcoding.net/assets/logo.png
description: Kubernetes Gateway API CRDs and cluster-level Gateway resources for drunk.charts
type: application
version: 1.0.0
appVersion: "v1.2.0"
keywords:
  - gateway-api
  - ingress
  - kubernetes
  - networking
home: https://github.com/baoduy/drunk.charts
sources:
  - https://github.com/baoduy/drunk.charts
  - https://github.com/kubernetes-sigs/gateway-api
maintainers:
  - name: baoduy
    email: drunkcoding@outlook.com

dependencies:
  - name: cert-manager
    version: v1.16.2
    repository: "https://charts.jetstack.io"
    condition: certManager.enabled
  - name: traefik
    version: 33.2.0
    repository: "https://traefik.github.io/charts"
    condition: traefik.enabled
