nginx:
  enabled: false
  fullnameOverride: 'drunk-nginx'

openldap:
  enabled: true
  #fullnameOverride: 'drunk-openldap'

proxy:
  enabled: true
  fullnameOverride: 'drunk-proxy'
  service:
    type: ClusterIP
  deployment:
    enabled: true
    ports:
      tcp: '3128'
  odSecurityContext: {}
  securityContext:
#    capabilities:
#      drop:
#        - ALL
    readOnlyRootFilesystem: false
    allowPrivilegeEscalation: true
    runAsNonRoot: false