apiVersion: v2
name: drunk-app
icon: https://drunkcoding.net/assets/logo.png
description: The drunkcoding template to deploy an application to Kubernetes
# A chart can be either an 'application' or a 'library' chart.
type: application
version: 1.2.6
appVersion: "latest"

dependencies:
  - name: drunk-lib
    version: 1.x.x
    #repository: "https://baoduy.github.io/drunk.charts/drunk-lib"
    repository: "file://../drunk-lib"
