# Default values for app.
nameOverride: 'drunk-blog'

global:
  image: 'baoduy2412/toolbox'
  tag: 'latest'
  imagePullPolicy: 'Always'

deployment:
  enabled: true
  ports:
    http: 80
  replicaCount: 1
  #liveness: '/healthz'
  #readiness: "/healthz/ready"

serviceAccount:
  create: false
  annotations: {}

service:
  enabled: false
  type: ClusterIP

podAnnotations: {}

podSecurityContext:
  fsGroup: 10000
  runAsUser: 10000
  runAsGroup: 10000
securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  runAsNonRoot: true

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  #targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}
