# Default values for app.
# fullnameOverride: "" # DONOT use this update in the chard name instead
nameOverride: 'drunk-test-app'

global:
  image: 'baoduy2412/astro-blog'
  tag: 'latest'
  imagePullPolicy: 'IfNotPresent'
  #imagePullSecret: 'abc'
  initContainer:
    image: 'baoduy2412/astro-blog'
    command: ['sh', '-c', 'echo Init complete;']

#Environments variables through configMap and secrets
configMap:
  hello: '1'

secrets:
  connectionString: "ABC"

# The flag to disable pod-deployment incase of Job/CronJob only deployment
deployment:
  enabled: true
  ports:
    http: 8080
    tcp: 9090
  replicaCount: 1
  liveness: '/healthz'
  #readiness: "/healthz/ready"
  args:
    - tunnel
    - '--no-autoupdate'
    - run
    - '--token'
    - $(token)

cronJobs:
- name: 'drunk-cjob-1'
  schedule: "* 0 * * *"
  command:
  - hello
- name: 'drunk-cjob-2'
  schedule: "* 0 * * *"
  restartPolicy: Always
  command:
  - hello-1
  - hello-2

jobs:
- name: 'drunk-job-1'
  command:
  - hello
- name: 'drunk-job-2'
  restartPolicy: Always
  command:
  - hello-1
  - hello-2

volumes:
- name: data-vol
  size: '2Gi'
  storageClassName: 'abc'
  accessMode: 'ReadWriteOnce'
  mountPath: '/data'
  subPath: 'abc.dev'
  readOnly: false
- name: tmp
  mountPath: '/tmp'
  readOnly: false
  emptyDir: true

serviceAccount:
  create: true
  annotations: {}

service:
  type: ClusterIP

podAnnotations: {}

podSecurityContext:
  fsGroup: 10000
  runAsUser: 10000
  runAsGroup: 10000
securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  runAsNonRoot: true

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
  - host: hello.drunkcoding.net
  tls: chart-example-tls

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 100
  #targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}
