{{- $root := . }}
{{- range $k, $v := .Values.proxies }}
{{- if or $v.enabled (eq $v.enabled nil) }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $k }}-ingress
  labels: {{ include "app.labels" $root | nindent 4 }}
  {{- with $v.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ $v.ingressClassName | default "nginx" }}
  {{- if $v.tlsSecret }}
  tls:
    - hosts:
        - {{ $v.ingressHost | default nil }}
      secretName: {{ $v.tlsSecret }}
  {{- end }}
  rules:
  - host: {{ $v.ingressHost | default nil }}
    http:
      paths:
      - path: {{ default (print "/" $k) $v.ingressPath }}
        pathType: Prefix
        backend:
          service:
            name: {{ $k }}-svc
            port:
              number: {{ $v.targetPort | default 443 }}
{{- end }}
{{- end }}