proxies:
  webhook:
    enabled: true
    ingressHost: localhost
    ingressPath: /webhook/?(.*)
    ingressClassName: "internal"
    #ingressTlsSecret: "secret-name"
    targetHost: "192.168.1.68"
    targetPort: 443
    targetMTlsCert:
      ca: "123"
      crt: "444"
      key: "555"
    annotations:
      kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/proxy-ssl-verify: "off"
      nginx.ingress.kubernetes.io/proxy-ssl-verify-depth: "1"

  webapp:
    enabled: true
    ingressHost: api.dev.local
    ingressPath: /webapp/?(.*)
    ingressTlsSecret: tls-dev-local
    targetHost: "webhook.site"
    targetPort: 443
    annotations:
      nginx.ingress.kubernetes.io/proxy-ssl-verify: "on"
      nginx.ingress.kubernetes.io/proxy-ssl-verify-depth: "1"
