cfTunnel:
  global:
    image: cloudflare/cloudflared
    tag: 'latest'
    imagePullPolicy: 'Always'

  deployment:
    enabled: true
    replicaCount: 2
    args:
      - tunnel
      - '--no-autoupdate'
      - run
      - '--token'
      - $(token)

  secrets:
    token: 'eyJhIjoiYzRiZjYyNTNhNTlkYWY3MGE0NDU4NjFjMjNiNDU3NzgiLCJ0IjoiYjA4MzQ4NzYtZDkzOC00MGM3LTk3YjktMTlmYTE2ZjczMjlhIiwicyI6Ik1tWXlOVE15TmprdE9EWTJaUzAwWVRkbExXRTNOalV0T0dNeVpqZzFNekU0WmpWaSJ9'

  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi

  podSecurityContext:
    fsGroup: 10000
    runAsUser: 10000
    runAsGroup: 10000
  securityContext:
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    runAsNonRoot: true