{{- $root := . }}
{{- range $k, $v := .Values.proxies }}
{{- if or $v.enabled (eq $v.enabled nil) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.name" $root }}-{{ $k }}-proxy-svc
  labels: {{ include "app.labels" $root | nindent 4 }}
spec:
  type: ExternalName
  externalName: {{ $v.targetHost }}
{{- end }}
{{- end }}