{{- $root := . }}
{{- range $k, $v := .Values.tlsSecrets }}
{{- if or $v.enabled (eq $v.enabled nil) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: tls-{{ $k }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $v.crt }}
  tls.key: {{ $v.key }}
  {{- if $v.ca }}
  ca.crt: {{ $v.ca }}
  {{- end }}
{{- end }}
{{- end }}