{{- $root := . }}
{{- range $k, $v := .Values.proxies }}
{{- if $v.targetMTlsCert }}
---
apiVersion: v1
kind: Secret
metadata:
  name: tls-{{ $k }}-ingress-proxy
type: kubernetes.io/tls
data:
  tls.crt: {{ $v.targetMTlsCert.crt | quote }}
  tls.key: {{ $v.targetMTlsCert.key | quote}}
  {{- if $v.targetMTlsCert.ca }}
  ca.crt: {{ $v.targetMTlsCert.ca | quote}}
  {{- end }}
{{- end }}
{{- end }}