{{- $root := . }}
{{- range .Values.cronJobs }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "app.name" $root }}-{{ .name }}
  labels:
    {{- include "app.labels" $root | nindent 4 }}
spec:
  schedule: "{{ .schedule }}"
  # Keep only one successful and one failed job history
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          automountServiceAccountToken: false
          {{- if $.Values.global.imagePullSecret }}
          imagePullSecrets:
             name: {{ $.Values.global.imagePullSecret }}
          {{- end }}
          serviceAccountName: {{ include "app.serviceAccountName" $root }}
          securityContext:
            {{- toYaml $.Values.podSecurityContext | nindent 12 }}
          restartPolicy: {{ .restartPolicy | default "OnFailure" }}
          containers:
          - name: {{ .name }}
            securityContext:
              {{- toYaml $.Values.securityContext | nindent 14 }}
            image: "{{ $.Values.global.image }}:{{ $.Values.global.tag | default $.Chart.AppVersion }}"
            imagePullPolicy: "{{ $.Values.global.imagePullPolicy | default "Always" }}"
           {{- with .command }}
            command:
              {{- toYaml . | nindent 12 }}
            {{- end }}
            envFrom:
            {{- if $.Values.configMap }}
              - configMapRef:
                  name: {{ include "app.fullname" $root }}-config
              {{- end }}
              {{- if $.Values.secrets }}
              - secretRef:
                  name: {{ include "app.fullname" $root }}-secret
              {{- end }}
            resources:
            {{- toYaml $.Values.resources | nindent 14 }}
            {{- if $.Values.volumes }}
            volumeMounts:
            {{- range $.Values.volumes }}
              - name: {{ .name }}
                readOnly: {{ .readOnly | default false }}
                mountPath: {{ .mountPath }}
              {{- if .subPath }}
                subPath: {{ .subPath }}
              {{- end }}
            {{- end }}
            {{- end }}
         {{- if $.Values.volumes }}
          volumes:
          {{- range $.Values.volumes }}
          - name: {{ .name }}
            persistentVolumeClaim:
              claimName: {{ include "app.name" $root }}-{{ .name }}
          {{- end }}
          {{- end }}
{{- end }}