{{- $root := . }}
{{- if .Values.deploymentEnabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.global.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "app.selectorLabels" . | nindent 8 }}
    spec:
      automountServiceAccountToken: false
      {{- if .Values.global.imagePullSecret }}
      imagePullSecrets:
        name: {{ .Values.global.imagePullSecret }}
      {{- end }}
      serviceAccountName: {{ include "app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      
      {{- if .Values.global.initContainer }}
      # Begin initContainers
      initContainers:
        - name: {{ include "app.name" . }}-init
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.global.initContainer.image }}"
          imagePullPolicy: "IfNotPresent"
          command: "{{ .Values.global.initContainer.command }}"
          envFrom:
          {{- if .Values.configMap }}
            - configMapRef:
                name: {{ include "app.name" . }}-config
          {{- end }}
          {{- if .Values.secrets }}
            - secretRef:
                name: {{ include "app.name" . }}-secret
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.volumes }}
          volumeMounts:
          {{- range .Values.volumes }}
            - name: {{ .name }}
              readOnly: {{ .readOnly | default false }}
              mountPath: {{ .mountPath }}
            {{- if .subPath }}
              subPath: {{ .subPath }}
            {{- end }}
          {{- end }}
          {{- end }}
      # End initContainers
      {{- end }}

      # Begin Containers
      containers:
        - name: {{ include "app.name" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.global.image }}:{{ .Values.global.tag | default .Chart.AppVersion }}"
          imagePullPolicy: "{{ .Values.global.imagePullPolicy | default "Always" }}"
          ports:
            - name: http
              containerPort: {{ .Values.global.port | default 8080 }}
              protocol: TCP
          {{- if .Values.global.liveness }}
          livenessProbe:
            httpGet:
              path: {{ .Values.global.liveness }}
              port: http
          {{- end }}
          {{- if .Values.global.readiness }}
          readinessProbe:
            httpGet:
              path: {{ .Values.global.readiness }}
              port: http
          {{- end }}
          envFrom:
          {{- if .Values.configMap }}
            - configMapRef:
                name: {{ include "app.name" . }}-config
          {{- end }}
          {{- if .Values.secrets }}
            - secretRef:
                name: {{ include "app.name" . }}-secret
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.volumes }}
          volumeMounts:
          {{- range .Values.volumes }}
            - name: {{ .name }}
              readOnly: {{ .readOnly | default false }}
              mountPath: {{ .mountPath }}
            {{- if .subPath }}
              subPath: {{ .subPath }}
            {{- end }}
          {{- end }}
          {{- end }}
      # End Containers
      
      {{- if .Values.volumes }}
      volumes:
      {{- range .Values.volumes }}
        - name: {{ .name }}
        {{- if .emptyDir }}
          emptyDir: {}
        {{- else }}
          persistentVolumeClaim:
            claimName: {{ include "app.name" $root }}-{{ .name }}
        {{- end }}
      {{- end }}
      {{- end }}
      
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}