{{- $root := . }}
{{- range .Values.jobs }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "app.name" $root }}-{{ .name }}-{{ randAlphaNum 5 | lower }}
  labels:
    {{- include "app.labels" $root | nindent 4 }}
spec:
  backoffLimit: 4
  # TTL set for 1 week after job completion
  ttlSecondsAfterFinished: 604800
  template:
    spec:
      automountServiceAccountToken: false
      {{- with $.Values.global.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 10 }}
      {{- end }}
      serviceAccountName: {{ include "app.serviceAccountName" $root }}
      securityContext:
      {{- toYaml $.Values.podSecurityContext | nindent 10 }}
      restartPolicy: {{ .restartPolicy | default "OnFailure" }}
      containers:
      - name: {{ .name }}
        securityContext:
        {{- toYaml $.Values.securityContext | nindent 12 }}
        image: "{{ $.Values.global.image }}:{{ $.Values.global.tag | default $.Chart.AppVersion }}"
        imagePullPolicy: "{{ $.Values.global.imagePullPolicy | default "Always" }}"
        {{- with .command }}
        command:
        {{- toYaml . | nindent 10 }}
        {{- end }}
        envFrom:
        {{- if $.Values.configMap }}
        - configMapRef:
            name: {{ include "app.fullname" $root }}-config
        {{- end }}
        {{- if $.Values.secrets }}
        - secretRef:
            name: {{ include "app.fullname" $root }}-secret
        {{- end }}
        resources:
        {{- toYaml $.Values.resources | nindent 14 }}
{{- end }}