{{- $root := . }}
{{- range .Values.volumes }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "app.name" $root }}-{{ .name }}
  labels:
    {{- include "app.labels" $root | nindent 4 }}
spec:
  resources:
    requests:
      storage: {{ .size | default "2Gi" }}
  volumeMode: Filesystem
  accessModes:
    - {{ .accessMode | default "ReadWriteOnce" }}
  storageClassName: {{ .storageClassName | default "" }}
{{- end }}