# ClusterIssuer resources (conditional)
{{- if .Values.certManager.enabled }}
{{- range .Values.certManager.clusterIssuers }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .name }}
  labels:
    {{- include "gateway.labels" $ | nindent 4 }}
spec:
  acme:
    server: {{ .server }}
    email: {{ .email }}
    privateKeySecretRef:
      name: {{ .privateKeySecretRef.name }}
    solvers:
    {{- toYaml .solvers | nindent 4 }}
{{- end }}
{{- end }}
