{{- if .Values.gatewayClass.enabled }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: {{ .Values.gatewayClass.name }}
  {{- with .Values.gatewayClass.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
    {{- with .Values.gatewayClass.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  controllerName: {{ .Values.gatewayClass.controllerName }}
  {{- with .Values.gatewayClass.description }}
  description: {{ . }}
  {{- end }}
  {{- with .Values.gatewayClass.parametersRef }}
  parametersRef:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
